### ISSUE TITLE
How are the S2 identifiers defined?

### ISSUE THREAD

**Issue by aletar89** [allenai/s2-folks#11]
There are two types of S2 identifiers as described in the [API](https://api.semanticscholar.org/api-docs/graph#tag/Paper-Data/operation/get_graph_get_paper):
```
<sha> - a Semantic Scholar ID, e.g. 649def34f8be52c8b66281af98ae884c09aef38b
CorpusId:<id> - Semantic Scholar numerical ID, e.g. 215416146
```
Can we always assume the `sha` is a string of 40 lowercase hex characters?
Can we always assume the `CorpusId` is a 32 bit integer?
Is there a way to convert from one to the other?

**Comment by wammar** [comment]
On it. Sorry for the delay @aletar89

**Comment by wammar** [comment]
Relaying the following info from our engineering team, with some edits:

There's a bit of necessary context before we can answer this question. One of the critical steps in our pipeline is to group or cluster several versions of the same paper which we obtained from different sources (e.g., arxiv and aclanthology). This is not a straightforward problem because some of the paper versions may have non-trivial differences in content, e.g., an earlier draft. 

> Can we always assume the sha is a string of 40 lowercase hex characters?

SHA is an identifier of a specific version of a paper. It's literally computed as a function of the file content. It is therefore not supposed to change over time. SHA is always a 40-char hex, but we wouldn't count on it being upper or lower case.

> Can we always assume the CorpusId is a 32 bit integer?

corpus IDs are 64-bit int.

> Is there a way to convert from one to the other?

You can use either ID to lookup the other using a query like this (sorry `corpusId` is not in the documentation yet; we'll address that soon): https://api.semanticscholar.org/graph/v1/paper/649def34f8be52c8b66281af98ae884c09aef38b?fields=paperId,corpusId
