### ISSUE TITLE
Confusing authors and program committee

### ISSUE THREAD

**Issue by kwchurch** [allenai/s2-folks#44]
https://www.semanticscholar.org/search?q=Map-Reduce%20for%20Machine%20Learning%20on%20Multicore&sort=relevance

This paper appeared in NIPS (now called NeurIPS).  It should not be hard to find

https://www.researchgate.net/profile/Gary-Bradski-4/publication/221617998_Map-Reduce_for_Machine_Learning_on_Multicore/links/00b4951c369007c315000000/Map-Reduce-for-Machine-Learning-on-Multicore.pdf

The authors should not be confused with the editors (program committee).

There are links on semantic scholar to slides (as opposed to paper): https://pdfs.semanticscholar.org/38af/f6df1accc456f6cda7d16d4b9ecf418ef21e.pdf

It would be good to distinguish authors from editors, and slides from papers.

**Comment by wammar** [comment]
Thanks for submitting this @kwchurch ! Agreed on both fronts, and we've made progress on these two issues but unfortunately there's no easy fix. Forwarding this to the data quality team to make sure it's tracked, but will keep it open.

**Comment by cfiorelli** [comment]
It sees the paper is now showing in semantic scholar's SERP, and authors list in our service compared to authors list in research gate are aligned. I dont see the link to the pdfs.semanticscholar.org resource any longer, though if the concern remains due to the fact that the resource is still accessible we can revisit. Let me know if i missed something. (sorry for the long delay catching up in chunks across a variety of areas. )
