### ISSUE TITLE
Q: How to obtain the full text of a certain paper through S2ORC?

### ISSUE THREAD

**Issue by MichaelZona** [allenai/s2-folks#69]
I am a computer science student and am now conducting research on inter-document document analysis. So Could you please guide me on how to obtain the full text of a certain paper through S2ORC? I found that most of things I can obtain are metadatas of the paper...

Thanks!

**Comment by vanivk1** [comment]
Hi, I have this question as well. Was there a resolution to this?

**Comment by cfiorelli** [comment]
@MichaelZona  @vanivk1 
We have since launched some pretty good documentation on S2ORC / datasets and will be continuing to improve this in coming months. Also for live and recent code examples please check our slack community.

Finally if you have any questions please update here (assuming this core need has passed since this issue is a bit old)

thank you both!
