### ISSUE TITLE
Paper Recommendations API for single paper recommending itself

### ISSUE THREAD

**Issue by de-code** [allenai/s2-folks#82]
**Describe the bug**

The Paper Recommendations API for a single paper seem to at least sometimes recommend the passed in paper.

For example asking for recommendations for `DOI:10.1101/2023.05.07.539746` includes as the first recommendation `DOI:10.1101/2023.05.07.539746`.

**To Reproduce**

e.g. response for `https://api.semanticscholar.org/recommendations/v1/papers/forpaper/DOI:10.1101/2023.05.07.539746?fields=externalIds&limit=3`

```json
{
  "recommendedPapers": [
    {
      "paperId": "7bf3e6af873bdc381b0f93a904c52b0a6ad34df2",
      "externalIds": {
        "DOI": "10.1101/2023.05.07.539746",
        "CorpusId": 258569034
      }
    },
    {
      "paperId": "06a01b2ea376302dd4bd62221007b8feec26827d",
      "externalIds": {
        "DOI": "10.1002/anie.202218064",
        "CorpusId": 257764561,
        "PubMed": "36970768"
      }
    },
    {
      "paperId": "a716e2207b725f4254a7d6cea3c27f1e22370dc7",
      "externalIds": {
        "PubMedCentral": "10073219",
        "DOI": "10.1038/s41421-023-00527-1",
        "CorpusId": 257915391,
        "PubMed": "37015924"
      }
    }
  ]
}
```

**Expected behavior**
The paper the recommendations are for shouldn't be part of the recommendations.

**Additional context**

The same request for the API taking a list doesn't show the same behaviour, at least for the same paper.

```bash
curl \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{"positivePaperIds":["DOI:10.1101/2023.05.07.539746"], "negativePaperIds": []}' \
  'https://api.semanticscholar.org/recommendations/v1/papers/?fields=externalIds&limit=3'
```

```json
{
  "recommendedPapers": [
    {
      "paperId": "2bdbb2a47647126181ffcb2bf9a049dbbdd647e5",
      "externalIds": {
        "DOI": "10.1101/2023.03.16.533055",
        "CorpusId": 257696775,
        "PubMed": "36993210"
      }
    },
    {
      "paperId": "821fff79971adb7abd421c400619d9c366500540",
      "externalIds": {
        "DOI": "10.1101/2023.04.12.536557",
        "CorpusId": 258171819
      }
    },
    {
      "paperId": "1bd6814d15e5605a1a500703ede32faa378f660e",
      "externalIds": {
        "DOI": "10.1101/2023.04.15.537025",
        "CorpusId": 258190719
      }
    }
  ]
}
```

The paper `10.1101/2023.05.07.539746` is not recommended as the first paper, or later on.

Or anywhere in the response:

```bash
curl \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{"positivePaperIds":["DOI:10.1101/2023.05.07.539746"], "negativePaperIds": []}' \
  'https://api.semanticscholar.org/recommendations/v1/papers/?fields=externalIds&limit=500' \
  | jq \
  | grep '10.1101/2023.05.07.539746'
```

Surprisingly, the recommendations are generally quite different. (e.g. three bioRxiv/medRxiv papers vs more journal articles)

**Comment by wammar** [comment]
I'm not surprised that the recommendations are different when you use the `papers/forpaper/` vs. `papers/`, because the implementation is quite different. In particular, `papers/forpaper/` is simply a k-nearest-neighbor search, while `papers/` trains a discriminative model using embeddings as features, then recommends KNN papers which the model is most confident about.

That said, I agree it's surprising to have the `papers/forpaper/` return the input paper as one of the results, hence marking this as a bug. Thank you for reporting this @de-code .

**Comment by giorgiosironi** [comment]
> In particular, papers/forpaper/ is simply a k-nearest-neighbor search, while papers/ trains a discriminative model using embeddings as features, then recommends KNN papers which the model is most confident about.

Sorry to go slightly off-topic, but could you point us to any relevant issue or documentation about this difference and any trade-offs? It sounds like the `/papers` implementation is more complex but perhaps higher in accuracy and/or more computationally expensive?

**Comment by cmwilhelm** [comment]
> Sorry to go slightly off-topic, but could you point us to any relevant issue or documentation about this difference and any trade-offs? It sounds like the `/papers` implementation is more complex but perhaps higher in accuracy and/or more computationally expensive?

The `papers/forpaper` implementation is substantially simpler and runs several orders of magnitude faster than the `/papers` model. The latter, however, is capable of incorporating both negative and positive signal, and makes use of TF-IDF as well as specter information in providing recommendations.

To the issue at hand, this looks like a simple bug in the KNN. My guess is FAISS either doesn't exclude vectors that identically match the probe vector (requiring us to filter it, which we are apparently not), OR our embedding has changed very slightly since index time, e.g. if we got some slightly updated / cleaned up abstract text. In the latter case, FAISS wouldn't be able to filter, but the old vector would likely still probably be the closest hit.

**Comment by AmberRose2** [comment]
Addressed in this [pr](https://github.com/allenai/s2-public-api/pull/329)
