### ISSUE TITLE
Article Author Affiliation from your API?

### ISSUE THREAD

**Issue by wammar** [allenai/s2-folks#85]
**Is your feature request related to a problem? Please describe.**
In the recent past, we used to extract the author affiliation associated with every article, but this is not available any longer.

**Describe the solution you'd like**
Can we get the author affiliation as listed on each article (i.e. the affiliations each authors listed in their article)?

**Describe alternatives you've considered**
Not provided by user.

**Additional context**
Created on behalf of [Nikos Pitsianis](https://semanticscholar.freshdesk.com/a/contacts/17034262386) (see [freshdesk ticket](https://semanticscholar.freshdesk.com/a/tickets/56796)).

**Comment by pitsianis** [comment]
Thanks!

**Comment by cfiorelli** [comment]
@pitsianis Looks like we do now offer affiliations for the author endpoint. 
https://api.semanticscholar.org/api-docs/graph#tag/Author-Data/operation/post_graph_get_authors

Thank you!

**Comment by pitsianis** [comment]
I am sorry if I did not make this clear, the request was about *author-affiliation associated with every article*, that is, where each author was as listed in each and every publication. Authors do move... 😄 

From the API, you do associate articles to authors and authors to affiliations, but it appears the affiliation is independent of the the article, and it can differ from the one listed on the article.

**Comment by cfiorelli** [comment]
Articles
Authors
Affiliations (venue)

**Comment by pitsianis** [comment]
Yes, that is correct. In the past, the article record contained the author record with an affiliation field, as it appeared on each specific article. Now, the article record points to an author record, which has the (latest?) affiliation of the author. Still, this affiliation is not necessarily the same as the one in the article because the author might have moved.
Thank you again for your efforts and the excellent service you are offering to the academic community.

**Comment by cfiorelli** [comment]
Affiliations remodeling work is on review this year. Logging this on 2024 prioritization agenda
